id: A56346B2F
title: Offering to the Dharma Guardians of the 'Neck-Pouch Dagger’ (Purba Gulkhukma)
  Cycle
type: translation
pechas:
- I84348A88
- IEB4BE939
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:50:57.290627
  last_modified_at: 2023-01-04 12:50:57.290647
  collections:
  - Khenchen Jigme Phuntsok Series
  - Works of Tibetan Masters
alignment_to_base:
  I84348A88/D284: C881
  IEB4BE939/62F6: C881
